// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "ai.provider": string;
      "ai.apiKey": string;
      "ai.baseUrl": string;
      "ai.model": string;
      "pomodoro.workMin": number;
      "pomodoro.breakMin": number;
      "locale": string;
    };
  }
}
